version: '3.3'
services:
  function:
    image: function
    build:
      dockerfile: function-simulator/Dockerfile
    depends_on:
      - db
  api:
    image: web-api
    build:
      dockerfile: api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: aPassw0rd?
      MYSQL_USER: sa
      MYSQL_PASSWORD: aPassw0rd!
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
volumes:
  db_data: 
networks:
  net:
    driver: bridge
